name: observability-stack

services:
  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=5GB'
      - '--web.enable-lifecycle'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - loki
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus

  loki:
    image: grafana/loki:3.4
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - ./loki/config.yaml:/etc/loki/local-config.yaml:ro
      - loki-data:/loki

  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    image: grafana/grafana:12.1
    ports:
      - "3000:3000"
    networks:
      - loki
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.102.0
    command: 
      - "--config=/etc/otel-collector-config.yaml"
    volumes:
      - "./otel-collector/config.yaml:/etc/otel-collector-config.yaml"
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - loki

volumes:
  prometheus-data:
  loki-data:

networks:
  loki: