apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy 
  orgId: 1
  url: http://observability-stack-loki-1:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false
- name: Prometheus
  type: prometheus
  url: http://observability-stack-prometheus-1:9090 
  isDefault: false
  access: proxy
  editable: true